
% Add different part folders to path

addpath('PreProcessing/');
addpath('Classification/');
addpath('Trajectory/');
addpath('Data/');


% Set deafault graphic settings

set(groot,  'DefaultLineLineWidth', 2, ...
            'DefaultTextInterpreter', 'LaTeX', ...
            'DefaultAxesFontSize', 30, ...
            'DefaultLegendInterpreter', 'LaTeX', ...
            'DefaultAxesLineWidth', 1.5, ...
            'DefaultStemLineWidth', 2.5, ...
            'DefaultAxesFontSize',30,...
            'DefaultFigureColor','w');
